# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.kernelPackages = pkgs.linuxPackages_latest;

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [ 
      vpl-gpu-rt
      vaapiIntel
      intel-media-driver
    ];
  };

  boot.kernelParams = [
    "mitigations=off"
    "i915.force_probe=!4c8b"
    "xe.force_probe=4c8b"
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8756f2d0-a56a-427c-9825-15d13147aafe";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2018-135E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # sudo mount -t nfs 192.168.49.21:/sas-16tb/ds-public /ds-public -o defaults,hard,intr,noexec,nosuid,_netdev,vers=4,fsc
  # fileSystems."/ds-public" = 
  #   { device = "192.168.49.21:/sas-16tb/ds-public";
  #     fsType = "nfs4";
  #     options = [ "defaults" "hard" "intr" "nosuid" "_netdev" "vers=4" "fsc" "x-systemd.after=network-online.target" ];
  #   };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a0392053-8099-4a52-919a-13b705fa3375"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
