// SPDX-License-Identifier: GPL-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 Chris Dell
//!
//! pctv320cx - Pinnacle PCTV 320cx ExpressCard analog capture driver.
//!
//! The card is a DiB0700 USB bridge with a Conexant CX25843 video decoder and
//! a DiB7000P OFDM demodulator.  The vendor's Linux driver (dvb-usb/dib0700)
//! only drives the DVB-T side: the analog front end is reachable only through
//! the vendor's Windows driver, and the decoder is invisible to Linux because
//! the DiB0700 I2C tunnel is not exposed as an i2c_adapter.
//!
//! This driver drives the analog path natively:
//!
//!   - downloads the DiB0700 firmware (same blob the DVB driver uses) so the
//!     bridge's microcontroller runs,
//!   - talks to the CX25843 over the bridge's vendor I2C tunnel,
//!   - programs the decoder for composite / S-Video in PAL or NTSC,
//!   - arms the bridge and streams BT.656 8-bit video over bulk-IN,
//!   - deframes BT.656 into UYVY (Cb Y Cr Y) frames and hands them to videobuf2.
//!
//! The V4L2 face (struct video_device, struct vb2_queue, the ioctl table and
//! the control handler) lives in v4l2-glue.c, because those are embedded C
//! structs with function-pointer tables that the Rust V4L2 abstractions do not
//! cover.  The two halves meet in pctv320cx.h: the C glue calls the driver
//! through struct pctv_ops, the driver calls back through the
//! pctv_glue_buffer_*() handoff helpers.
//!
//! Hardware reverse-engineering notes: FINDINGS.md in this directory.

//! The kernel's own crates require an explicit `unsafe {}` around every unsafe
//! operation, even inside an `unsafe fn`.  This module opts out for the moment
//! to keep the bring-up code readable; tightening it up is a pre-upstream
//! cleanup item.
#![allow(unsafe_op_in_unsafe_fn)]

module! {
    type: Pctv320cx,
    name: "pctv320cx",
    authors: ["Chris Dell"],
    description: "Pinnacle PCTV 320cx analog capture (composite / S-Video)",
    license: "GPL",
    firmware: ["dvb-usb-dib0700-1.20.fw", "v4l-cx25840.fw"],
    params: {
        debug: u32 {
            default: 1,
            description: "Log decoder identity and dropped capture buffers.",
        },
    },
}

use core::ffi::{c_char, c_int, c_void};

use kernel::{
    c_str,
    prelude::*,
    sync::atomic::{ordering::Relaxed, Atomic},
    sync::{new_spinlock, SpinLock},
    time,
    time::delay::{fsleep, udelay},
};

mod bindings {
    // Generated by bindgen from pctv320cx.h (see Kbuild); it lands next to
    // this file in the build directory.  The allowances match what the
    // in-tree `bindings` crate uses for the same generated code.
    #![allow(
        dead_code,
        non_camel_case_types,
        non_snake_case,
        non_upper_case_globals,
        improper_ctypes,
        unreachable_pub,
        unsafe_op_in_unsafe_fn,
        clippy::all
    )]

    // Manual definitions for the blocklisted types, as rust/bindings/lib.rs
    // does.
    type __kernel_size_t = usize;
    type __kernel_ssize_t = isize;
    type __kernel_ptrdiff_t = isize;

    include!("pctv320cx_bindings.rs");
}

// SAFETY: `__BindgenBitfieldUnit` is a plain byte storage wrapper that is all
// zeroes by its own default.

// ---------------------------------------------------------------------------
// DiB0700 vendor control interface
// ---------------------------------------------------------------------------

/// Vendor control requests (drivers/media/usb/dvb-usb/dib0700.h).
///
/// bmRequestType must carry recipient=device (0x04): the vendor firmware
/// NACKs the recipient=0 form that the in-tree dib0700 driver sends, which is
/// why that driver never gets a reply off this card.
const REQTYPE_VENDOR_OUT: u8 = 0x44;
const REQTYPE_VENDOR_IN: u8 = 0xc4;

const RQ_SET_USB_XFER_LEN: u8 = 0x00;
const RQ_ENABLE_VIDEO: u8 = 0x0f;
const RQ_SET_I2C_PARAM: u8 = 0x10;
const RQ_NEW_I2C_READ: u8 = 0x12;
const RQ_NEW_I2C_WRITE: u8 = 0x13;
const RQ_GET_VERSION: u8 = 0x15;
const RQ_SET_CLOCK: u8 = 0x0b;
const RQ_SET_GPIO: u8 = 0x0c;

/// The 8-bit address the bridge answers I2C tunnel traffic at; the gate
/// control is a write to this pseudo-address.
const BRIDGE_I2C_ADDR: u8 = 0x40;

/// Bulk OUT endpoint 1 is the firmware download pipe.
const EP_FW_OUT: u8 = 0x01;

// V4L2 uapi values the Rust core needs.  They are #defines/enums in
// uapi/linux/videodev2.h that bindgen does not emit for this header; spelled
// out here (with the header as the source of truth) rather than re-included.
const PCTV_FIELD_INTERLACED: u32 = 4;		/* V4L2_FIELD_INTERLACED */
const PCTV_COLORSPACE_SMPTE170M: u32 = 1;	/* V4L2_COLORSPACE_SMPTE170M */
const PCTV_COLORSPACE_470BG: u32 = 6;		/* V4L2_COLORSPACE_470_SYSTEM_BG */
const PCTV_STD_PAL_B: u64 = 0x00000001;		/* V4L2_STD_PAL_B */
const PCTV_STD_NTSC_M: u64 = 0x00001000;		/* V4L2_STD_NTSC_M */

/// Bridge firmware, same blob the in-tree dib0700 driver requests.
const BRIDGE_FIRMWARE: &CStr = c_str!("dvb-usb-dib0700-1.20.fw");

/// CX25843 firmware (the decoder's microcode), loaded through the bridge.
const DECODER_FIRMWARE: &CStr = c_str!("v4l-cx25840.fw");

// TODO(next chunk): capture geometry, register tables and the driver state.

// ---------------------------------------------------------------------------
// Capture geometry
// ---------------------------------------------------------------------------

/// Bytes in one whole BT.656 line as the bridge ships it: 4 sync + 1440
/// active + 284 blanking.  Verified against the captures in FINDINGS.md.
const LINE_BYTES: usize = 1728;
const SYNC_BYTES: usize = 4;
const ACTIVE_BYTES: usize = 1440;

/// Active lines per field, as the decoder emits them after trimming blanking.
/// PAL: 288, measured on hardware - every complete field in the mode-2
/// captures is exactly 288 lines (FINDINGS.md section 12.2).  NTSC: 243, the
/// 525-line half of cx25840_std_setup()'s vactive=487; not yet verified on
/// hardware.
const PAL_LINES: usize = 288;
const NTSC_LINES: usize = 243;

/// Bytes per active line kept in the frame: 720 pixels of UYVY (Cb Y Cr Y).
const ACTIVE_PIXEL_BYTES: usize = 1440;

/// Capture URBs in flight.  8 x 64 KiB covers ~1.5 frames of BT.656, which is
/// comfortably more than the 2 s videobuf2 timeout.
const NUM_URBS: usize = 8;
const URB_BYTES: usize = 65536;
/// Scratch holding one field's active lines (max PAL) before they are
/// vertically rescaled into the frame.  A field arrives with up to ~5% of its
/// lines missing (mode-2 bandwidth ceiling); writing the survivors directly
/// into their nominal rows makes every dropped line shift the rest of the
/// field up and the picture jitters.  The scratch lets the field end be found
/// first, then resamples the N captured lines onto the fixed 288-row grid.
const FIELD_SCRATCH_BYTES: usize = PAL_LINES * ACTIVE_PIXEL_BYTES;
/// Bulk-IN endpoint number that carries the analog capture stream (the
/// in-tree dib0700 devices table uses stream endpoint 2 for this card;
/// FINDINGS.md section 11.2: only 0x82 ever delivers).
const CAPTURE_EP_NUM: u8 = 2;
/// Staging buffer for the bulk-OUT writes.  The USB core refuses to DMA from
/// the stack (hcd.c: transfer buffer is on stack) and from the vmalloc'd
/// firmware blob, so every bulk-OUT payload is copied here first.  A firmware
/// record is at most 4 + 255 + 1 bytes.
const FW_BUF_BYTES: usize = 512;

// TV standard selector.  The C glue translates between v4l2_std_id and this;
// the card has no RF tuner, so it only picks the decoder's line/colour
// system.
const STD_PAL: u32 = 0;
const STD_NTSC: u32 = 1;

// Errnos, spelled out to keep the core independent of the kernel's error
// modules.
const EIO: c_int = 5;
const ENOMEM: c_int = 12;
const ENODEV: c_int = 19;
const EINVAL: c_int = 22;
const EOVERFLOW: c_int = 75;

// V4L2 control ids, mirrored here so the core does not depend on bindgen
// emitting the uapi macros.
const CID_BRIGHTNESS: u32 = 0x009a0902;
const CID_CONTRAST: u32 = 0x009a0903;
const CID_SATURATION: u32 = 0x009a0904;
const CID_HUE: u32 = 0x009a0905;

// videobuf2 buffer states are NOT mirrored here: the glue picks the state
// itself (pctv_glue_buffer_done() always completes with VB2_BUF_STATE_DONE)
// so the Rust side never has to know this kernel enum.  A hand-copied value
// is what broke the first streaming run (it was 0 = DEQUEUED, and
// vb2_buffer_done() then warned and returned the frames as ERROR).

// ---------------------------------------------------------------------------
// Driver state
// ---------------------------------------------------------------------------

/// One capture URB, its DMA buffer, and the driver it belongs to.  The
/// parent pointer stays valid because the driver struct is pinned.
struct Urb {
    urb: *mut bindings::urb,
    buffer: *mut u8,
    /// DMA handle returned by usb_alloc_coherent() for @buffer.  It has to be
    /// the one handed to usb_free_coherent(), and it has to be written into
    /// the URB (URB_NO_TRANSFER_DMA_MAP) or the HCD maps the buffer a second
    /// time and leaves a different address in transfer_dma.
    dma: bindings::dma_addr_t,
    parent: *mut Pctv320cxInner,
}

impl Urb {
    const fn empty() -> Self {
        Self {
            urb: core::ptr::null_mut(),
            buffer: core::ptr::null_mut(),
            dma: 0,
            parent: core::ptr::null_mut(),
        }
    }
}


/// The driver.
///
/// `udev` is the raw `struct usb_device` behind the interface the shim handed
/// us; the interface itself is owned by the USB core for the lifetime of the
/// binding, which is exactly the lifetime of this object.
#[pin_data]
struct Pctv320cxInner {
    udev: *mut bindings::usb_device,
    intf: *mut bindings::usb_interface,
    glue: *mut bindings::pctv_glue,

    /// Bulk-IN endpoint actually advertised by the streaming interface.
    ep_in: u8,

    /// Capture URB pool.
    urbs: [Urb; NUM_URBS],

    /// DMA-safe staging buffer for the bulk-OUT writes (firmware records,
    /// jumpram).  Allocated with the URB pool, freed with it.
    fw_buf: *mut u8,

    /// Scratch for the field being deframed (see FIELD_SCRATCH_BYTES).
    /// Allocated with the URB pool, freed with it.
    field_buf: *mut u8,

    /// Streaming state, read by the URB completion (softirq) and written by
    /// start/stop (process context).
    streaming: Atomic<bool>,
    /// Set when a completion could not find a buffer to fill.
    dropped: Atomic<u32>,

    /// Deframer, shared by the URB completions.  Completions of different
    /// URBs may run on different CPUs, hence the spinlock.
    #[pin]
    deframer: SpinLock<Deframer>,

    /// Negotiated state.  Guarded by the video device lock held by the C glue
    /// for every ioctl, so no extra locking is needed for the ioctl path.
    std_sel: u32,
    input: u32,
    fmt: bindings::pctv_fmt,

    /// Decoder state we have to remember because CX25843 registers are
    /// write-only in places (clock/standard/enable).
    clock_on: bool,
    decoder_ready: bool,
}

// SAFETY: the fields are either plain data, or pointers into objects owned by
// the USB core / videobuf2 whose lifetime brackets this struct.  All mutation
// is serialised by the video device lock, except `streaming`/`dropped` which
// are atomic.
unsafe impl Send for Pctv320cxInner {}
unsafe impl Sync for Pctv320cxInner {}

// ---------------------------------------------------------------------------
// DiB0700 vendor request plumbing
// ---------------------------------------------------------------------------

/// I2C tunnel control byte: start/stop conditions plus the transfer length in
/// the low 6 bits (dib0700_i2c_write_new()).
const I2C_CTRL_START: u8 = 1 << 7;
const I2C_CTRL_STOP: u8 = 1 << 6;

/// Adapter generation: 1 selects the "new" (firmware >= 1.20) I2C engine.
const I2C_BUS_NEW: u8 = 1;

/// The CX25843 sits at 7-bit 0x44 on the bridge's I2C bus.
const CX_I2C_ADDR: u8 = 0x44;

/// The DiB7000P demod, only used to release its hold on the parallel bus.
const DEMOD_I2C_ADDR: u8 = 0x48;

impl Pctv320cxInner {
    /// Vendor OUT control transfer: the request byte is the first byte of the
    /// data stage, exactly like dib0700_ctrl_wr().
    unsafe fn ctrl_wr(&self, record: &[u8]) -> c_int {
        let mut buf = [0u8; 96];
        if record.len() > buf.len() {
            return -EOVERFLOW;
        }
        buf[..record.len()].copy_from_slice(record);
        bindings::usb_control_msg_send(
            self.udev,
            0,
            record[0],
            REQTYPE_VENDOR_OUT,
            0,
            0,
            buf.as_ptr() as *const c_void,
            record.len() as u16,
            1000,
            0,
        )
    }

    /// Vendor IN control transfer.
    unsafe fn ctrl_rd(&self, request: u8, value: u16, index: u16, out: &mut [u8]) -> c_int {
        bindings::usb_control_msg_recv(
            self.udev,
            0,
            request,
            REQTYPE_VENDOR_IN,
            value,
            index,
            out.as_mut_ptr() as *mut c_void,
            out.len() as u16,
            1000,
            0,
        )
    }

    /// Is the bridge's microcontroller running?  A cold device (no firmware)
    /// stalls this request.  Exactly the in-tree form: vendor IN, request
    /// 0x15, wValue = wIndex = 0, 16 byte reply
    /// (hw / rom / ram / fwtype versions).
    unsafe fn firmware_loaded(&self) -> bool {
        let mut rx = [0u8; 16];
        let ret = self.ctrl_rd(RQ_GET_VERSION, 0, 0, &mut rx);
        if ret < 0 {
            kernel::pr_info!("GET_VERSION: errno {} - bridge is cold\n", ret);
            false
        } else {
            kernel::pr_info!(
                "GET_VERSION: hw 0x{:08x} rom 0x{:08x} ram 0x{:08x} fw 0x{:08x}\n",
                u32::from_be_bytes([rx[0], rx[1], rx[2], rx[3]]),
                u32::from_be_bytes([rx[4], rx[5], rx[6], rx[7]]),
                u32::from_be_bytes([rx[8], rx[9], rx[10], rx[11]]),
                u32::from_be_bytes([rx[12], rx[13], rx[14], rx[15]]),
            );
            true
        }
    }


    /// Total byte count the bridge will push through the bulk-IN pipe before
    /// it stops (0 = unlimited).  Firmware >= 1.21 only.
    unsafe fn set_usb_transfer_length(&self, bytes: u32) -> c_int {
        self.ctrl_wr(&[
            RQ_SET_USB_XFER_LEN,
            ((bytes >> 8) & 0xff) as u8,
            (bytes & 0xff) as u8,
        ])
    }

    /// Bridge PLL: 72 MHz, clock output on GP3
    /// (dib0700_ctrl_clock(d, 72, 1) -> buf[1] = (en_pll<<7)|(pll_src<<6)|
    /// (pll_range<<5)|(gp3<<4) = 0xb0, prediv 2, loopdiv 24, free_div 0,
    /// scaler 0x4c).  This is the form `pctv_probe clock` proved on this card.
    unsafe fn set_clock(&self) -> c_int {
        self.ctrl_wr(&[RQ_SET_CLOCK, 0xb0, 0x00, 0x02, 0x00, 0x18, 0x00, 0x00, 0x00, 0x4c])
    }

    /// I2C bus timing, in kHz (dib0700_i2c_set_params()).
    unsafe fn set_i2c_param(&self, khz: u32) -> c_int {
        let slow = (30000 / khz) as u16;
        let fast = (72000 / khz) as u16;
        self.ctrl_wr(&[
            RQ_SET_I2C_PARAM,
            0x00,
            (slow >> 8) as u8,
            (slow & 0xff) as u8,
            (fast >> 8) as u8,
            (fast & 0xff) as u8,
            (fast >> 8) as u8,
            (fast & 0xff) as u8,
        ])
    }

    unsafe fn gpio(&self, pin: u8, dir: u8, value: u8) -> c_int {
        self.ctrl_wr(&[RQ_SET_GPIO, pin, ((dir & 1) << 7) | ((value & 1) << 6)])
    }

    /// ANALOG framing on the bulk-IN pipe (dib0700_enable_video()).
    /// byte1 = (on<<4) | mode, byte2 = channel byte (0x01), byte3 = 0.
    ///
    /// The kernel/vendor only know mode 0 (MPEG2) and mode 1 ("analog"), but
    /// mode 1 hands over just the active part of each line (1444-byte blocks,
    /// 15.3 MB/s) and cannot carry a PAL signal in real time (27.0 MB/s), so
    /// the bridge drops a third of the lines.  **Mode 2 (`0x12`) sends the
    /// whole BT.656 line (EAV + blanking + SAV + active = 1728 bytes) at
    /// 25.6 MB/s = ~95% of lines** - FINDINGS.md section 11.  The deframer
    /// below is written for exactly that 1728-byte framing.
    unsafe fn enable_video(&self, mode: u8) -> c_int {
        self.ctrl_wr(&[RQ_ENABLE_VIDEO, mode, 0x01, 0x00])
    }

    /// Release the bridge's four capture channels before arming a stream:
    /// each is cleared by writing its bit with mode 0 (FINDINGS.md section
    /// 11 - without this a channel left over from a previous mode-switch
    /// keeps the bridge from starting).
    unsafe fn release_channels(&self) {
        for bit in [0x01u8, 0x02, 0x04, 0x08] {
            let _ = self.ctrl_wr(&[RQ_ENABLE_VIDEO, 0x00, bit, 0x00]);
        }
    }

    /// Bulk OUT, used for the firmware records and the jumpram request.
    ///
    /// The payload goes through the driver's own DMA-safe staging buffer:
    /// the bridge blob comes from request_firmware(), which for a 33 KiB
    /// image hands back vmalloc memory, and the USB core refuses to DMA-map
    /// that (usb_hcd_map_urb_for_dma: rejecting DMA map of vmalloc memory).
    /// An on-stack buffer is refused too, so this cannot be a local array.
    unsafe fn bulk_write(&self, endpoint: u8, data: &[u8]) -> c_int {
        if self.fw_buf.is_null() || data.len() > FW_BUF_BYTES {
            return -EOVERFLOW;
        }
        core::ptr::copy_nonoverlapping(data.as_ptr(), self.fw_buf, data.len());
        let pipe = bindings::pctv_usb_sndbulkpipe(self.udev, endpoint);
        let mut actual = 0i32;
        bindings::usb_bulk_msg(
            self.udev,
            pipe,
            self.fw_buf as *mut c_void,
            data.len() as c_int,
            &mut actual,
            2000,
        )
    }

    /// Open or close the bridge's I2C gate towards the CX25843.
    unsafe fn i2c_gate(&self, on: bool, addr7: u8) -> c_int {
        let val: u16 = if on {
            ((addr7 as u32) << 9) as u16
        } else {
            0x100
        };
        self.i2c_write(
            BRIDGE_I2C_ADDR,
            &[0x04, 0x01, (val >> 8) as u8, (val & 0xff) as u8],
        )
    }

    /// I2C write through the tunnel (dib0700_i2c_write_new()).
    unsafe fn i2c_write(&self, addr7: u8, data: &[u8]) -> c_int {
        if data.len() > 0x3f {
            return -EOVERFLOW;
        }
        let mut record = [0u8; 96];
        record[0] = RQ_NEW_I2C_WRITE;
        record[1] = addr7 << 1;
        record[2] = I2C_CTRL_START | I2C_CTRL_STOP | (data.len() as u8 & 0x3f);
        record[3] = (I2C_BUS_NEW << 4) & 0x30;
        record[4..4 + data.len()].copy_from_slice(data);
        self.ctrl_wr(&record[..4 + data.len()])
    }


    /// Write one CX25843 register: 16-bit sub-address plus one data byte.
    unsafe fn cx_w(&self, reg: u16, val: u8) -> c_int {
        self.cx_burst(reg, &[val])
    }

    /// Write a burst of CX25843 registers behind one 16-bit sub-address.
    unsafe fn cx_burst(&self, reg: u16, data: &[u8]) -> c_int {
        let len = data.len() + 2;
        if len > 0x3f {
            return -EOVERFLOW;
        }
        let mut record = [0u8; 96];
        record[0] = RQ_NEW_I2C_WRITE;
        record[1] = (CX_I2C_ADDR << 1) as u8;
        record[2] = I2C_CTRL_START | I2C_CTRL_STOP | (len as u8 & 0x3f);
        record[3] = (I2C_BUS_NEW << 4) & 0x30;
        record[4] = (reg >> 8) as u8;
        record[5] = (reg & 0xff) as u8;
        record[6..6 + data.len()].copy_from_slice(data);
        self.i2c_gate(true, CX_I2C_ADDR);
        let ret = self.ctrl_wr(&record[..6 + data.len()]);
        self.i2c_gate(false, 0);
        ret
    }

    /// Read one CX25843 register.  Two I2C transactions behind one gate:
    /// a sub-address write (start, **no stop**) followed by the read (repeated
    /// start implied, stop, 1 byte).  wIndex carries the bus byte (0x10 =
    /// frontend bus), *not* the register - the register only travels in the
    /// sub-address write.  This is the form `pctv_probe cxr` proved on this
    /// card; putting the register in wIndex makes the firmware look at the
    /// EEPROM bus instead.
    unsafe fn cx_r(&self, reg: u16) -> c_int {
        let mut record = [0u8; 6];
        record[0] = RQ_NEW_I2C_WRITE;
        record[1] = (CX_I2C_ADDR << 1) as u8;
        record[2] = I2C_CTRL_START | 2; // start, no stop, 2 address bytes
        record[3] = (I2C_BUS_NEW << 4) & 0x30;
        record[4] = (reg >> 8) as u8;
        record[5] = (reg & 0xff) as u8;
        self.i2c_gate(true, CX_I2C_ADDR);
        let ret = self.ctrl_wr(&record);
        if ret < 0 {
            self.i2c_gate(false, 0);
            return ret;
        }
        let mut out = [0u8; 1];
        let value: u16 = (((I2C_CTRL_STOP | 1) as u16) << 8)
            | ((CX_I2C_ADDR << 1) as u16);
        let index: u16 = ((I2C_BUS_NEW << 4) & 0x30) as u16;
        let ret = self.ctrl_rd(RQ_NEW_I2C_READ, value, index, &mut out);
        self.i2c_gate(false, 0);
        if ret < 0 {
            ret
        } else {
            out[0] as c_int
        }
    }

}

// ---------------------------------------------------------------------------
// Bring-up
// ---------------------------------------------------------------------------

/// Records of the bridge firmware blob, walked the way the vendor's loader
/// does: [len, addr_hi, addr_lo, type, data:len, checksum].
fn fw_record_len(blob: &[u8], pos: usize) -> Option<usize> {
    if pos + 5 > blob.len() {
        return None;
    }
    let len = blob[pos] as usize;
    if pos + 4 + len + 1 > blob.len() {
        return None;
    }
    Some(len)
}

impl Pctv320cxInner {
    /// Upload the DiB0700 microcontroller firmware and jump to it.  Without
    /// this the bridge answers no vendor request at all.
    unsafe fn load_bridge_firmware(&self) -> Result {
        if self.firmware_loaded() {
            return Ok(());
        }

        // The firmware loader keys its search (and its devm bookkeeping) off
        // the interface's struct device - not off the interface itself, and
        // not off the driver cookie that drvdata will hold once probe
        // finishes (which has not happened yet at this point).
        let dev = &mut (*self.intf).dev as *mut bindings::device;
        let fw = bindings::pctv_request_fw(dev, BRIDGE_FIRMWARE.as_char_ptr() as *const i8);
        if fw.is_null() {
            return Err(Error::from_errno(-ENODEV));
        }
        let blob =
            unsafe { core::slice::from_raw_parts((*fw).data, (*fw).size as usize) };
        kernel::pr_info!("bridge firmware blob: {} bytes\n", blob.len());

        let mut pos = 0usize;
        let mut records = 0usize;
        while let Some(len) = fw_record_len(blob, pos) {
            let rec = &blob[pos..pos + len + 5];
            let ret = self.bulk_write(EP_FW_OUT, rec);
            if ret < 0 {
                kernel::pr_warn!(
                    "fw record at {} ({} bytes) failed: errno {}\n",
                    pos,
                    rec.len(),
                    ret
                );
                bindings::pctv_release_fw(dev, fw);
                return Err(Error::from_errno(-EIO));
            }
            records += 1;
            if rec[3] == 0x01 {
                break;
            }
            pos += len + 5;
        }
        kernel::pr_info!("downloaded {} firmware records ({} bytes)\n", records, pos);

        // jumpram -> 0x70000000, then give the 8051 time to start.
        let ret = self.bulk_write(EP_FW_OUT, &[0x08, 0x00, 0x00, 0x00, 0x70, 0x00, 0x00, 0x00]);
        if ret < 0 {
            kernel::pr_warn!("jumpram request failed: errno {}\n", ret);
            return Err(Error::from_errno(-EIO));
        }
        bindings::pctv_release_fw(dev, fw);
        fsleep(time::Delta::from_millis(500));
        if !self.firmware_loaded() {
            kernel::pr_warn!("bridge did not answer GET_VERSION after jumpram\n");
            return Err(Error::from_errno(-EIO));
        }
        Ok(())
    }

    /// The stk7700ph board init for this card: bridge clock, I2C timing and
    /// the GPIOs that power the decoder and the demod.
    unsafe fn board_init(&self) -> Result {
        self.set_clock();
        self.set_i2c_param(100);

        /* GPIO6 is the bridge's power/enable line (the in-tree driver leaves
         * the device "on GPIO6", and its board init for this family is
         * GPIO6=1, 9=1, 4=1, 7=1, 10 pulse, [0=1]).  The Windows trace's
         * first write is 6=0, but that is the *pre-download* pair; the
         * post-download sequence that actually runs the chip drives it high.
         */
        self.gpio(6, 1, 1);
        fsleep(time::Delta::from_millis(20));
        self.gpio(9, 1, 1);
        self.gpio(4, 1, 1);
        self.gpio(7, 1, 1);
        self.gpio(10, 1, 0);
        fsleep(time::Delta::from_millis(10));
        self.gpio(10, 1, 1);
        fsleep(time::Delta::from_millis(20));
        self.gpio(0, 1, 1);
        fsleep(time::Delta::from_millis(10));
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// CX25843 decoder
// ---------------------------------------------------------------------------

/// CX25843 register: video input mux.
const CX_REG_INPUT: u16 = 0x103;
/// CX25843 register: INPUT_MODE / OUTPUT_MODE / VBIT (cx25840_g/s_input()).
const CX_REG_INPUT_MODE: u16 = 0x401;
/// CX25843 picture controls, exactly as the in-tree cx25840 driver maps them
/// (cx25840_set_ctrl()): brightness 0x414 = val - 128, contrast 0x415 = val
/// << 1, saturation 0x420/0x421 = val << 1, hue 0x422 = val.
const CX_REG_BRIGHTNESS: u16 = 0x414;
const CX_REG_CONTRAST: u16 = 0x415;
const CX_REG_SATURATION: u16 = 0x420;
const CX_REG_SATURATION_U: u16 = 0x421;
const CX_REG_HUE: u16 = 0x422;
/// CX25843 registers: horizontal and vertical timing (cx25840_std_setup()).
const CX_REG_HBLANK: u16 = 0x470;
/// CX25843 register: standard select (0x49f).
const CX_REG_STD: u16 = 0x49f;
/// CX25843 registers: status (0x40d/0x40e: bit 0x20 of 0x40e = signal detect).
const CX_REG_STATUS_A: u16 = 0x40d;
const CX_REG_STATUS_B: u16 = 0x40e;
const CX_STATUS_SIGNAL: u8 = 0x20;
/// CX25843 registers: parallel video output enable (0x115/0x116).
const CX_REG_OUT_A: u16 = 0x115;
const CX_REG_OUT_B: u16 = 0x116;
/// CX25843 microcontroller: firmware data window and control.
const CX_REG_FW_DATA: u16 = 0x802;
const CX_REG_FW_COUNT_LO: u16 = 0x800;
const CX_REG_FW_COUNT_HI: u16 = 0x801;
const CX_REG_CR: u16 = 0x803;
const CX_CR_RESET: u8 = 0x0b;
const CX_CR_RUN: u8 = 0x03;
const CX_CR_INT_ENABLE: u8 = 0x10;

/// Per-standard timing, from cx25840_std_setup().
struct StdTiming {
    std_reg: u8,
    hblank: u16,
    hactive: u16,
    burst: u8,
    vblank: u16,
    vactive: u16,
    vblank656: u8,
    subcarrier: u32,
    comb: u8,
    luma_lpf: u8,
    uv_lpf: u8,
}

const TIMING_PAL: StdTiming = StdTiming {
    std_reg: 0x11,
    hblank: 132,
    hactive: 720,
    burst: 93,
    vblank: 36,
    vactive: 580,
    vblank656: 40,
    subcarrier: 688739,
    comb: 0x20,
    luma_lpf: 2,
    uv_lpf: 1,
};

const TIMING_NTSC: StdTiming = StdTiming {
    std_reg: 0x14,
    hblank: 122,
    hactive: 720,
    burst: 0x5b,
    vblank: 26,
    vactive: 487,
    vblank656: 26,
    subcarrier: 556063,
    comb: 0x66,
    luma_lpf: 1,
    uv_lpf: 1,
};

/// One input: the CX25843 mux value (reg 0x103) that selects it.  S-Video
/// feeds luma and chroma into two decoder inputs; the mux value is all that
/// has to change - 0x401 stays at 0xc0, which is what the on-hardware
/// S-Video captures used (FINDINGS.md section 12.1).
struct InputDef {
    mux: u8,
}

/// Video1 / Video2 / Video3 are the three decoder inputs the card's dongle
/// wires up; S-Video feeds luma and chroma into two of them.
const INPUTS: [InputDef; 4] = [
    InputDef { mux: 0xf0 }, // composite, Video1
    InputDef { mux: 0xf1 }, // composite, Video2
    InputDef { mux: 0xf2 }, // composite, Video3
    InputDef { mux: 0xd0 },  // S-Video (Video2 + Video3)
];

impl Pctv320cxInner {
    /// Read-modify-write a CX25843 register.
    unsafe fn cx_or(&self, reg: u16, mask: u8, val: u8) -> c_int {
        let cur = self.cx_r(reg);
        if cur < 0 {
            return cur;
        }
        self.cx_w(reg, ((cur as u8) & mask) | val)
    }

    /// Load the decoder's microcode through the bridge's I2C tunnel.  The
    /// blob is streamed into the 0x802 window in 46-byte bursts.
    unsafe fn load_decoder_firmware(&self) -> Result {
        let dev = &mut (*self.intf).dev as *mut bindings::device;
        let fw = bindings::pctv_request_fw(dev, DECODER_FIRMWARE.as_char_ptr() as *const i8);
        if fw.is_null() {
            return Err(Error::from_errno(-ENODEV));
        }
        let blob =
            unsafe { core::slice::from_raw_parts((*fw).data, (*fw).size as usize) };

        // Halt the microcontroller, poke the standard reset sequence, then
        // feed the image.
        let cr = self.cx_r(CX_REG_CR);
        if cr >= 0 {
            self.cx_w(CX_REG_CR, (cr as u8) & !CX_CR_INT_ENABLE);
        }
        self.cx_w(0x000, 0x04);
        self.cx_w(0x159, 0x23);
        self.cx_w(0x15a, 0x87);
        self.cx_w(0x15b, 0x06);
        udelay(time::Delta::from_micros(10));
        self.cx_w(0x159, 0xe1);
        udelay(time::Delta::from_micros(10));
        self.cx_w(0x15a, 0x86);
        self.cx_w(0x159, 0xe0);
        self.cx_w(0x159, 0xe1);
        self.cx_w(0x15b, 0x10);
        self.cx_w(0x15d, 0xe3);
        self.cx_w(0x15e, 0x86);
        self.cx_w(0x15f, 0x06);
        udelay(time::Delta::from_micros(10));
        self.cx_w(0x15d, 0xe1);
        self.cx_w(0x15d, 0xe0);
        self.cx_w(0x15d, 0xe1);
        self.cx_w(0x136, 0x0a);
        self.cx_w(0x13c, 0x01);
        self.cx_w(0x13c, 0x00);

        self.cx_w(CX_REG_FW_COUNT_LO, 0);
        self.cx_w(CX_REG_FW_COUNT_HI, 0);
        self.cx_w(CX_REG_CR, CX_CR_RESET);
        self.cx_w(0x000, 0x20);

        let mut off = 0usize;
        while off < blob.len() {
            let len = core::cmp::min(blob.len() - off, 46);
            if self.cx_burst(CX_REG_FW_DATA, &blob[off..off + len]) < 0 {
                bindings::pctv_release_fw(dev, fw);
                return Err(Error::from_errno(-EIO));
            }
            off += len;
        }

        self.cx_w(0x000, 0);
        self.cx_w(CX_REG_CR, CX_CR_RUN);

        // The decoder counts the bytes it took; a mismatch means the image
        // stalled and the decoder will not lock.
        let lo = self.cx_r(CX_REG_FW_COUNT_LO);
        let hi = self.cx_r(CX_REG_FW_COUNT_HI);
        bindings::pctv_release_fw(dev, fw);
        if lo < 0 || hi < 0 || (((hi as u32) << 8) | (lo as u32)) != blob.len() as u32 {
            return Err(Error::from_errno(-EIO));
        }
        Ok(())
    }
}

impl Pctv320cxInner {
    /// The decoder registers that must be set once its microcode is running:
    /// parallel output on, VBI/teletext windows cleared.
    unsafe fn decoder_post_firmware(&self) {
        self.cx_w(0x115, 0x8c);
        self.cx_w(0x116, 0x07);
        self.cx_w(0x118, 0x02);
        self.cx_w(0x4a5, 0x80);
        self.cx_w(0x4a5, 0x00);
        self.cx_w(0x402, 0x00);
        self.cx_or(0x4a2, !0x10, 0x10);
        self.cx_w(0x8d3, 0x1f);
        self.cx_w(0x8e3, 0x03);
        self.cx_w(0x914, 0xa0);
        self.cx_w(0x918, 0xa0);
        self.cx_w(0x919, 0x01);
        self.cx_w(0x809, 0x04);
        self.cx_w(0x8cf, 0x0f);
        self.cx_or(CX_REG_CR, !CX_CR_INT_ENABLE, CX_CR_INT_ENABLE);
    }

    /// Program the decoder for one TV standard (cx25840_std_setup()).
    unsafe fn std_setup(&self, std_sel: u32) {
        let t = if std_sel == STD_NTSC {
            &TIMING_NTSC
        } else {
            &TIMING_PAL
        };

        self.cx_w(CX_REG_STD, t.std_reg);
        self.cx_w(CX_REG_HBLANK, t.hblank as u8);
        self.cx_w(
            CX_REG_HBLANK + 1,
            ((((t.hblank >> 8) & 3) | (t.hactive << 4)) & 0xff) as u8,
        );
        self.cx_w(CX_REG_HBLANK + 2, (t.hactive >> 4) as u8);
        self.cx_w(CX_REG_HBLANK + 3, t.burst);
        self.cx_w(CX_REG_HBLANK + 4, t.vblank as u8);
        self.cx_w(
            CX_REG_HBLANK + 5,
            ((((t.vblank >> 8) & 3) | (t.vactive << 4)) & 0xff) as u8,
        );
        self.cx_w(CX_REG_HBLANK + 6, (t.vactive >> 4) as u8);
        self.cx_w(CX_REG_HBLANK + 7, t.vblank656);
        self.cx_w(CX_REG_HBLANK + 8, 0x1f);
        self.cx_w(CX_REG_HBLANK + 9, 0x02);
        self.cx_w(CX_REG_HBLANK + 10, (t.luma_lpf << 6) | ((t.uv_lpf << 4) & 0x30));
        self.cx_w(CX_REG_HBLANK + 11, t.comb);
        self.cx_w(CX_REG_HBLANK + 12, (t.subcarrier & 0xff) as u8);
        self.cx_w(CX_REG_HBLANK + 13, ((t.subcarrier >> 8) & 0xff) as u8);
        self.cx_w(CX_REG_HBLANK + 14, ((t.subcarrier >> 16) & 0xff) as u8);
        // 0x47f: PAL/NTSC chroma band selection.
        self.cx_w(CX_REG_HBLANK + 15, if std_sel == STD_NTSC { 0x00 } else { 0x01 });

        // Keep the parallel video output to the bridge enabled.
        let a = self.cx_r(CX_REG_OUT_A);
        if a >= 0 {
            self.cx_w(CX_REG_OUT_A, (a as u8) | 0x0c);
        }
        let b = self.cx_r(CX_REG_OUT_B);
        if b >= 0 {
            self.cx_w(CX_REG_OUT_B, (b as u8) | 0x04);
        }
    }

    /// Select composite or S-Video (cx25840_g/s_input()).
    unsafe fn input_setup(&self, input: u32) {
        let def = match INPUTS.get(input as usize) {
            Some(d) => d,
            None => return,
        };
        self.cx_w(CX_REG_INPUT, def.mux);
        // 0x401: bit 7 CAGCEN on, bit 6 CKILLEN.  The vendor init leaves this
        // at 0x60, which pins the chroma path: every even byte of the BT.656
        // stream comes back as exactly 0x80 (FINDINGS.md section 9).  0xc0 is
        // the value that makes Cb/Cr carry signal, verified on hardware for
        // both composite and S-Video.
        self.cx_w(CX_REG_INPUT_MODE, 0xc0);
    }

    /// Apply one V4L2 control to the decoder.  The CX25843 ranges are the
    /// ones the in-tree driver uses: brightness 0..255 (0x80 = 1.0),
    /// contrast/saturation 0..127 (0x40 = 1.0), hue -128..127.
    unsafe fn ctrl_apply(&self, id: u32, value: c_int) -> c_int {
        match id {
            CID_BRIGHTNESS => self.cx_w(CX_REG_BRIGHTNESS, (value - 128) as u8),
            CID_CONTRAST => self.cx_w(CX_REG_CONTRAST, ((value << 1) & 0xff) as u8),
            CID_SATURATION => {
                let v = ((value << 1) & 0xff) as u8;
                self.cx_w(CX_REG_SATURATION, v);
                self.cx_w(CX_REG_SATURATION_U, v)
            }
            CID_HUE => self.cx_w(CX_REG_HUE, (value & 0xff) as u8),
            _ => -EINVAL,
        }
    }

    /// Is there a video signal on the selected input?  Bit 0x20 of 0x40e is
    /// the signal-detect flag; it needs the colour killer settled, so the
    /// caller polls it rather than reading once.
    unsafe fn signal_present(&self) -> bool {
        let v = self.cx_r(CX_REG_STATUS_B);
        v >= 0 && ((v as u8) & CX_STATUS_SIGNAL) != 0
    }

    /// Log the decoder's lock state (0x40d = detected format, 0x40e bit 0x20
    /// = video signal present).  0x40e only settles once the colour killer
    /// has made up its mind, so poll briefly before reporting.  Without a
    /// lock the bridge has nothing to stream - a locked state is a
    /// prerequisite for frames, and the input connector on these cards is
    /// known to be intermittent (FINDINGS.md section 10).
    unsafe fn log_signal_state(&self, stage: &str) -> bool {
        let mut a = 0;
        let mut b = 0;
        let mut locked = false;
        for _ in 0..10 {
            a = self.cx_r(CX_REG_STATUS_A);
            b = self.cx_r(CX_REG_STATUS_B);
            locked = b >= 0 && ((b as u8) & CX_STATUS_SIGNAL) != 0;
            if locked {
                break;
            }
            fsleep(time::Delta::from_millis(20));
        }
        if a < 0 || b < 0 {
            kernel::pr_warn!(
                "signal check ({}): decoder did not answer (0x40d errno {}, 0x40e errno {})\n",
                stage,
                a,
                b
            );
            return false;
        }
        if locked {
            kernel::pr_info!(
                "signal check ({}): 0x40d = 0x{:02x} 0x40e = 0x{:02x} -> LOCKED\n",
                stage,
                a as u8,
                b as u8
            );
        } else {
            kernel::pr_warn!(
                "signal check ({}): 0x40d = 0x{:02x} 0x40e = 0x{:02x} -> NO SIGNAL (capture will be empty)\n",
                stage,
                a as u8,
                b as u8
            );
        }
        locked
    }

    /// The DiB7000P demod shares the bridge's 8-bit parallel bus with the
    /// decoder.  Unless its output drivers are tri-stated the two drivers
    /// fight over the bus and nothing reaches the FIFO: this is the one step
    /// the vendor's Windows driver does that the DVB driver never has to.
    unsafe fn demod_release_bus(&self) {
        self.demod_w(1286, 0x0000);
        self.demod_w(1287, 0x0003);
        self.demod_w(235, 0x0022);
        self.demod_w(236, 1792);
    }

    /// 16-bit register write to the demod over the same I2C tunnel.
    unsafe fn demod_w(&self, reg: u16, val: u16) {
        let _ = self.i2c_write(
            DEMOD_I2C_ADDR,
            &[
                (reg >> 8) as u8,
                (reg & 0xff) as u8,
                (val >> 8) as u8,
                (val & 0xff) as u8,
            ],
        );
    }

    /// Full decoder bring-up: microcode, standard, input, controls.
    unsafe fn decoder_setup(&self) -> Result {
        let id = self.cx_r(0x100);
        if id < 0 {
            kernel::pr_warn!("CX25843 did not answer the I2C tunnel (reg 0x100: errno {})\n", id);
        } else {
            kernel::pr_info!("CX25843 chip id (reg 0x100) = 0x{:02x}\n", id);
        }
        if id != 0x34 {
            kernel::pr_warn!("CX25843 not detected (reg 0x100 = 0x{:02x})\n", id);
        } else {
            // 0x34 is the CX25843 chip id: the part is there, so (re)load the
            // microcode and program the post-firmware registers.  The
            // microcode lives in RAM and is lost on power-cycle, so this runs
            // on every probe (same as the in-tree cx25840 driver).
            self.load_decoder_firmware()?;
            self.decoder_post_firmware();
        }
        self.std_setup(self.std_sel);
        self.input_setup(self.input);
        self.log_signal_state("bring-up");
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Capture: bulk-IN streaming and BT.656 deframing
// ---------------------------------------------------------------------------

/// BT.656 8-bit sync switch: FF 00 00 followed by the status byte.
const SAV0: u8 = 0xff;
const SAV1: u8 = 0x00;
const SAV2: u8 = 0x00;
/// BT.656 status byte (`FF 00 00 XY`): bit 7 is fixed 1, bit 6 is F (which
/// field), bit 5 is V (vertical blanking), bit 4 is H (0 = SAV, start of
/// active video; 1 = EAV, end of active video).  Bits 3..0 are the protection
/// bits.  The earlier code tested bit 0 (a protection bit) as H, which
/// accepted EAV codes such as `0xda` and rejected the field-2 SAV `0xc7`.
const SAV_STATUS_V: u8 = 0x20;
const SAV_STATUS_H: u8 = 0x10;

/// Deframer state, only touched from the URB completion (softirq) and reset
/// when streaming starts.
///
/// The CX25843 emits whole BT.656 lines (mode 2): SAV, active video, EAV,
/// blanking.  Active lines carry V=0; the vertical-blanking lines carry V=1
/// and their 1440 bytes are blanking level, not picture.
///
/// Fields are delimited by the **V** bit, not by F.  The decoder flips F one
/// line early (a single active line at the end of a field already carries the
/// next field's F) and that lone line is fragile: if the bridge drops it, an
/// F-based boundary slips a whole line.  The vertical-blanking run is ~22
/// lines wide, so the V=1 -> V=0 transition is a far steadier anchor.  Each
/// V=0 run is one field; consecutive runs alternate output parity (even/odd
/// rows = V4L2_FIELD_INTERLACED).
///
/// Mode 2 still drops ~5% of the active lines (the bridge tops out at
/// 25.6 MB/s and PAL needs 27.0).  Writing the survivors straight into their
/// nominal rows lets every drop pull the rest of the field up - that is the
/// visible vertical jitter.  Instead each field is accumulated in a scratch
/// buffer and, once its true line count N is known, resampled onto the fixed
/// 288-row grid, which spreads the missing lines evenly instead of shifting
/// everything below them.
struct Deframer {
    /// Buffer currently being filled (from the vb2 handoff), and its address.
    vb: *mut bindings::vb2_buffer,
    addr: *mut u8,
    size: u32,
    /// Active lines copied into the scratch for the field in progress.
    field_lines: u32,
    /// Output parity of the field in progress (0 = even rows, 1 = odd rows).
    parity: usize,
    /// Parities already flushed into the current buffer.
    filled: [bool; 2],
    /// True while a V=0 active region is being captured.
    in_field: bool,
    /// Output lines per field for the selected standard.
    h_out: usize,
    /// Frames still to throw away before handing one out.  Streaming joins
    /// the BT.656 stream mid-field, so the first assembled buffer holds the
    /// tail of one field and the head of the next; discard it (and restart
    /// in the same buffer) so userspace's first frame is complete.
    preroll: u32,
}

impl Deframer {
    const fn new() -> Self {
        Self {
            vb: core::ptr::null_mut(),
            addr: core::ptr::null_mut(),
            size: 0,
            field_lines: 0,
            parity: 1,
            filled: [false, false],
            in_field: false,
            h_out: PAL_LINES,
            preroll: 1,
        }
    }

    fn reset(&mut self, std_sel: u32) {
        let h_out = if std_sel == STD_NTSC {
            NTSC_LINES
        } else {
            PAL_LINES
        };
        *self = Self {
            h_out,
            ..Self::new()
        };
    }

    /// Take the next videobuf2 buffer.  Returns false when the queue is dry.
    unsafe fn acquire(&mut self, glue: *mut bindings::pctv_glue) -> bool {
        self.vb = bindings::pctv_glue_next_buffer(glue);
        if self.vb.is_null() {
            self.addr = core::ptr::null_mut();
            self.size = 0;
            return false;
        }
        self.addr = bindings::pctv_glue_buffer_addr(self.vb) as *mut u8;
        self.size = bindings::pctv_glue_buffer_size(self.vb);
        self.filled = [false, false];
        true
    }

    /// Resample the field's `field_lines` scratch lines onto `h_out` output
    /// rows and interleave them into the videobuf2 buffer at output parity
    /// `parity`.  Linear interpolation in 8-bit fixed point; the scratch holds
    /// UYVY, so byte-wise blending stays within the luma or the chroma samples.
    unsafe fn flush_field(
        &mut self,
        glue: *mut bindings::pctv_glue,
        scratch: *mut u8,
        parity: usize,
    ) {
        let n = self.field_lines as usize;
        if self.vb.is_null() || self.addr.is_null() || scratch.is_null() {
            self.filled[parity] = true;
            self.finish_frame(glue, parity);
            return;
        }
        let h_out = self.h_out;
        if n == 1 {
            for j in 0..h_out {
                let off = (2 * j + parity) * ACTIVE_PIXEL_BYTES;
                if off + ACTIVE_PIXEL_BYTES > self.size as usize {
                    break;
                }
                core::ptr::copy_nonoverlapping(scratch, self.addr.add(off), ACTIVE_PIXEL_BYTES);
            }
        } else if n > 1 {
            let denom = (h_out - 1) as u64;
            for j in 0..h_out {
                let off = (2 * j + parity) * ACTIVE_PIXEL_BYTES;
                if off + ACTIVE_PIXEL_BYTES > self.size as usize {
                    break;
                }
                let t = (j as u64) * ((n - 1) as u64);
                let i0 = (t / denom) as usize;
                let frac = (((t % denom) * 256) / denom) as u32;
                let i1 = core::cmp::min(i0 + 1, n - 1);
                let src0 = scratch.add(i0 * ACTIVE_PIXEL_BYTES);
                let src1 = scratch.add(i1 * ACTIVE_PIXEL_BYTES);
                let dst = self.addr.add(off);
                for k in 0..ACTIVE_PIXEL_BYTES {
                    let a = core::ptr::read(src0.add(k)) as u32;
                    let b = core::ptr::read(src1.add(k)) as u32;
                    core::ptr::write(dst.add(k), ((a * (256 - frac) + b * frac) >> 8) as u8);
                }
            }
        }
        self.filled[parity] = true;
        self.finish_frame(glue, parity);
    }

    /// Once both parities have been flushed the frame is complete: hand it to
    /// videobuf2 (or discard it while the startup preroll lasts).
    unsafe fn finish_frame(&mut self, glue: *mut bindings::pctv_glue, _parity: usize) {
        if !(self.filled[0] && self.filled[1]) {
            return;
        }
        self.filled = [false, false];
        if self.vb.is_null() {
            // Queue was dry when the frame was assembled; nothing to hand over.
            return;
        }
        if self.preroll > 0 {
            // Startup frame: keep the buffer and refill it.
            self.preroll -= 1;
            return;
        }
        // Both fields in: report the whole buffer, not just up to the last
        // line written (the fields interleave, so a variable bytesused makes
        // raw dumps impossible to frame align).
        bindings::pctv_glue_buffer_done(glue, self.vb, self.size);
        self.vb = core::ptr::null_mut();
        self.addr = core::ptr::null_mut();
    }
}

impl Pctv320cxInner {
    /// Push one bulk-IN payload through the deframer, completing buffers as
    /// they fill up.  Called from the URB completion, so it takes the pieces
    /// it needs rather than `&self`.
    unsafe fn deframe(
        glue: *mut bindings::pctv_glue,
        dropped: &Atomic<u32>,
        d: &mut Deframer,
        data: &[u8],
        scratch: *mut u8,
    ) {
        let mut pos = 0usize;
        while pos + SYNC_BYTES + ACTIVE_BYTES <= data.len() {
            if data[pos] != SAV0 || data[pos + 1] != SAV1 || data[pos + 2] != SAV2 {
                pos += 1;
                continue;
            }
            let status = data[pos + SYNC_BYTES - 1];

            // Only the SAV (H=0) sits immediately before active video; the
            // EAV (H=1) ends the line.
            if status & SAV_STATUS_H != 0 {
                pos += 1;
                continue;
            }

            if status & SAV_STATUS_V != 0 {
                // Vertical blanking: the field that just ended is complete.
                // Resample it into the buffer before moving on.
                if d.in_field {
                    let parity = d.parity;
                    d.flush_field(glue, scratch, parity);
                    d.in_field = false;
                }
                pos += LINE_BYTES;
                continue;
            }

            // V=0: an active line.  The first one after blanking opens a new
            // field; consecutive fields alternate output parity.
            if !d.in_field {
                d.parity ^= 1;
                d.field_lines = 0;
                d.in_field = true;
                if d.vb.is_null() && !d.acquire(glue) {
                    // No buffer to fill: drop the rest of this URB.
                    dropped.fetch_add(1, Relaxed);
                    return;
                }
            }

            let line = d.field_lines as usize;
            if !scratch.is_null() && line < FIELD_SCRATCH_BYTES / ACTIVE_PIXEL_BYTES {
                core::ptr::copy_nonoverlapping(
                    data.as_ptr().add(pos + SYNC_BYTES),
                    scratch.add(line * ACTIVE_PIXEL_BYTES),
                    ACTIVE_BYTES,
                );
                d.field_lines += 1;
            }

            // A line is always 1728 bytes on the wire: 4 sync + 1440 active
            // + 4 EAV + 280 blanking.  Skipping the whole line also keeps the
            // marker search in phase.
            pos += LINE_BYTES;
        }
    }
}

// ---------------------------------------------------------------------------
// Streaming
// ---------------------------------------------------------------------------

impl Pctv320cxInner {
    /// Allocate the capture URBs and their coherent buffers.
    unsafe fn alloc_urbs(&mut self) -> Result {
        if self.fw_buf.is_null() {
            self.fw_buf = bindings::pctv_kmalloc(FW_BUF_BYTES) as *mut u8;
            if self.fw_buf.is_null() {
                return Err(Error::from_errno(-ENOMEM));
            }
        }
        if self.field_buf.is_null() {
            self.field_buf = bindings::pctv_vmalloc(FIELD_SCRATCH_BYTES) as *mut u8;
            if self.field_buf.is_null() {
                return Err(Error::from_errno(-ENOMEM));
            }
        }
        for i in 0..NUM_URBS {
            let urb = bindings::usb_alloc_urb(0, bindings::pctv_gfp_kernel());
            if urb.is_null() {
                return Err(Error::from_errno(-ENOMEM));
            }
            let mut dma = 0u64;
            let buffer = bindings::usb_alloc_coherent(
                self.udev,
                URB_BYTES,
                bindings::pctv_gfp_kernel(),
                &mut dma as *mut u64 as *mut bindings::dma_addr_t,
            ) as *mut u8;
            if buffer.is_null() {
                bindings::usb_free_urb(urb);
                return Err(Error::from_errno(-ENOMEM));
            }
            self.urbs[i] = Urb {
                urb,
                buffer,
                dma: dma as bindings::dma_addr_t,
                parent: core::ptr::null_mut(),
            };
        }
        Ok(())
    }

    unsafe fn free_urbs(&mut self) {
        for u in self.urbs.iter_mut() {
            if u.urb.is_null() {
                continue;
            }
            bindings::usb_kill_urb(u.urb);
            if !u.buffer.is_null() {
                bindings::usb_free_coherent(
                    self.udev,
                    URB_BYTES,
                    u.buffer as *mut c_void,
                    u.dma,
                );
                u.buffer = core::ptr::null_mut();
            }
            bindings::usb_free_urb(u.urb);
            u.urb = core::ptr::null_mut();
        }
        if !self.fw_buf.is_null() {
            bindings::pctv_kfree(self.fw_buf as *mut c_void);
            self.fw_buf = core::ptr::null_mut();
        }
        if !self.field_buf.is_null() {
            bindings::pctv_vfree(self.field_buf as *const c_void);
            self.field_buf = core::ptr::null_mut();
        }
    }

    /// Arm the bridge and submit the capture URBs.
    unsafe fn stream_start(&mut self) -> c_int {
        // ANALOG framing, MODE 2 (0x12): whole BT.656 lines (1728 bytes) at
        // ~25.6 MB/s.  Mode 1 (0x11, what the vendor/kernel use) delivers only
        // the active part of each line and cannot sustain PAL; mode 0 (0x10)
        // runs the data through the TS multiplexer and yields no BT.656 at
        // all.  See FINDINGS.md section 11.
        self.release_channels();
        if !self.log_signal_state("stream-start") {
            kernel::pr_warn!("arming the bridge anyway, but no signal is locked\n");
        }
        if self.enable_video(0x12) < 0 {
            return -EIO;
        }
        self.set_usb_transfer_length(0);

        self.deframer.lock().reset(self.std_sel);
        self.streaming.store(true, Relaxed);

        let mut submitted = 0;
        for i in 0..NUM_URBS {
            let pipe = bindings::pctv_usb_rcvbulkpipe(self.udev, self.ep_in);
            self.urbs[i].parent = self as *mut Pctv320cxInner;
            let (urb, buffer) = (self.urbs[i].urb, self.urbs[i].buffer);
            let ctx = &mut self.urbs[i] as *mut Urb;
            bindings::pctv_usb_fill_bulk_urb(
                urb,
                self.udev,
                pipe,
                buffer as *mut c_void,
                URB_BYTES as c_int,
                Some(Pctv320cxInner::urb_complete),
                ctx as *mut c_void,
            );
            bindings::pctv_urb_use_coherent(urb, self.urbs[i].dma);
            if bindings::usb_submit_urb(urb, bindings::pctv_gfp_kernel()) < 0 {
                break;
            }
            submitted += 1;
        }
        if submitted == 0 {
            self.stream_stop();
            return -EIO;
        }
        kernel::pr_info!(
            "streaming on endpoint 0x{:02x}: {} URBs submitted\n",
            self.ep_in,
            submitted
        );
        0
    }

    /// Unarm the bridge and reap the capture URBs.
    unsafe fn stream_stop(&mut self) {
        self.streaming.store(false, Relaxed);
        for u in self.urbs.iter() {
            if !u.urb.is_null() {
                bindings::usb_kill_urb(u.urb);
            }
        }
        // 0x0f/0x00: streaming off.
        self.enable_video(0x00);

        // If the deframer was halfway through a buffer, hand it back to
        // videobuf2 in QUEUED state - otherwise it stays ACTIVE forever and
        // videobuf2 warns ("stop_streaming operation is leaving buffer N in
        // active state") and the buffer leaks.
        let mut d = self.deframer.lock();
        if !d.vb.is_null() {
            bindings::pctv_glue_buffer_requeue(self.glue, d.vb);
            d.vb = core::ptr::null_mut();
            d.addr = core::ptr::null_mut();
        }
    }

    /// Bulk-IN completion (softirq context).
    unsafe extern "C" fn urb_complete(urb: *mut bindings::urb) {
        let ctx = (*urb).context as *mut Urb;
        if ctx.is_null() {
            return;
        }
        let p = (*ctx).parent;
        if p.is_null() {
            return;
        }

        let status = (*urb).status;
        let actual = (*urb).actual_length;
        if (*p).streaming.load(Relaxed) {
            if status == 0 && actual > 0 {
                let data = core::slice::from_raw_parts((*ctx).buffer, actual as usize);
                let mut guard = (*p).deframer.lock();
                Self::deframe((*p).glue, &(*p).dropped, &mut *guard, data, (*p).field_buf);
            } else if status != 0 {
                // A halt on the pipe (the device dropped FIFO data) or a
                // short transfer: count it, the next submit clears the halt.
                (*p).dropped.fetch_add(1, Relaxed);
            }
            // Keep the pipe running.
            bindings::usb_submit_urb(urb, bindings::pctv_gfp_atomic());
        }
    }
}

// ---------------------------------------------------------------------------
// Glue callbacks
// ---------------------------------------------------------------------------

/// The C glue holds a `void *` cookie; every callback recovers the driver
/// from it.
unsafe fn drv(cookie: *mut c_void) -> &'static mut Pctv320cxInner {
    &mut *(cookie as *mut Pctv320cxInner)
}

unsafe extern "C" fn op_get_fmt(cookie: *mut c_void, out: *mut bindings::pctv_fmt) -> c_int {
    let d = drv(cookie);
    *out = d.fmt;
    0
}

/// Clamp a requested format without touching the hardware.
unsafe fn clamp_fmt(std_sel: u32, fmt: &mut bindings::pctv_fmt) {
    let (lines_per_field, _) = geometry(std_sel);
    let height = (lines_per_field * 2) as u32;

    fmt.width = 720;
    fmt.height = height;
    fmt.bytesperline = ACTIVE_PIXEL_BYTES as u32;
    fmt.sizeimage = (ACTIVE_PIXEL_BYTES * lines_per_field * 2) as u32;
    fmt.field = PCTV_FIELD_INTERLACED;
    fmt.colorspace = if std_sel == STD_NTSC {
        PCTV_COLORSPACE_SMPTE170M
    } else {
        PCTV_COLORSPACE_470BG
    };
}

fn geometry(std_sel: u32) -> (usize, u32) {
    if std_sel == STD_NTSC {
        (NTSC_LINES, 30000)
    } else {
        (PAL_LINES, 25000)
    }
}

unsafe extern "C" fn op_validate_fmt(cookie: *mut c_void, fmt: *mut bindings::pctv_fmt) -> c_int {
    let d = drv(cookie);
    clamp_fmt(d.std_sel, &mut *fmt);
    0
}

unsafe extern "C" fn op_apply_fmt(cookie: *mut c_void, fmt: *const bindings::pctv_fmt) -> c_int {
    let d = drv(cookie);
    let mut f = *fmt;
    clamp_fmt(d.std_sel, &mut f);
    d.fmt = f;
    (*d.deframer.lock()).reset(d.std_sel);
    0
}

unsafe extern "C" fn op_get_input(cookie: *mut c_void, index: *mut u32) -> c_int {
    *index = drv(cookie).input;
    0
}

unsafe extern "C" fn op_set_input(cookie: *mut c_void, index: u32) -> c_int {
    let d = drv(cookie);
    if index >= INPUTS.len() as u32 {
        return -EINVAL;
    }
    d.input = index;
    if d.decoder_ready {
        d.input_setup(index);
    }
    0
}

unsafe extern "C" fn op_get_std(cookie: *mut c_void, std_sel: *mut u32) -> c_int {
    *std_sel = drv(cookie).std_sel;
    0
}

unsafe extern "C" fn op_set_std(cookie: *mut c_void, std_sel: u32) -> c_int {
    let d = drv(cookie);
    if std_sel != STD_PAL && std_sel != STD_NTSC {
        return -EINVAL;
    }
    d.std_sel = std_sel;
    if d.decoder_ready {
        d.std_setup(std_sel);
    }
    let (lines_per_field, _) = geometry(std_sel);
    clamp_fmt(std_sel, &mut d.fmt);
    d.fmt.height = (lines_per_field * 2) as u32;
    (*d.deframer.lock()).reset(std_sel);
    0
}

unsafe extern "C" fn op_set_ctrl(cookie: *mut c_void, id: u32, value: c_int) -> c_int {
    // Before the decoder is up there is nothing to write to; report success so
    // the control handler (and userspace) does not fail on a card whose
    // firmware is missing.
    if !drv(cookie).decoder_ready {
        return 0;
    }
    let d = drv(cookie);
    if !d.decoder_ready {
        return 0;
    }
    let ret = d.ctrl_apply(id, value);
    if ret < 0 && ret != -EINVAL {
        return ret;
    }
    0
}

unsafe extern "C" fn op_get_signal(cookie: *mut c_void, signal: *mut u32) -> c_int {
    let d = drv(cookie);
    *signal = if d.decoder_ready && d.signal_present() { 1 } else { 0 };
    0
}

unsafe extern "C" fn op_start_streaming(cookie: *mut c_void) -> c_int {
    drv(cookie).stream_start()
}

unsafe extern "C" fn op_stop_streaming(cookie: *mut c_void) {
    drv(cookie).stream_stop();
}

// ---------------------------------------------------------------------------
// Probe / disconnect
// ---------------------------------------------------------------------------

/// Bulk-IN endpoint of the streaming interface: the bridge exposes two bulk
/// IN endpoints (TS and analog), pick the 512-byte-packet one that is not the
/// firmware pipe.
unsafe fn find_bulk_in_ep(intf: *mut bindings::usb_interface) -> c_int {
    let alt = (*intf).cur_altsetting;
    if alt.is_null() {
        return -ENODEV;
    }
    let count = (*alt).desc.bNumEndpoints as usize;
    let eps = core::slice::from_raw_parts((*alt).endpoint, count);
    let mut first: c_int = -ENODEV;
    for ep in eps {
        if !bindings::pctv_usb_endpoint_is_in(&ep.desc) {
            continue;
        }
        if bindings::pctv_usb_endpoint_maxpkt(&ep.desc) as usize & 0x7ff != 512 {
            continue;
        }
        let num = bindings::pctv_usb_endpoint_num(&ep.desc);
        // The 320cx exposes three bulk-IN endpoints (0x81/0x82/0x83) and only
        // **EP 2 (0x82)** ever carries the capture stream - FINDINGS.md
        // section 11.2, and the in-tree dib0700 devices table (stream
        // endpoint 2).  Reading 0x81 simply never completes a URB.
        if num == CAPTURE_EP_NUM {
            return (num | 0x80) as c_int;
        }
        if first < 0 {
            first = (num | 0x80) as c_int;
        }
    }
    first
}

/// Static description of the device for the C glue.
fn glue_info() -> bindings::pctv_glue_info {
    bindings::pctv_glue_info {
        card: b"Pinnacle PCTV 320cx\0".as_ptr() as *const c_char,
        bus_info: b"usb-pctv320cx\0".as_ptr() as *const c_char,
        input_names: [
            b"Composite 1\0".as_ptr() as *const c_char,
            b"Composite 2\0".as_ptr() as *const c_char,
            b"Composite 3\0".as_ptr() as *const c_char,
            b"S-Video\0".as_ptr() as *const c_char,
        ],
        num_inputs: INPUTS.len() as u32,
        stds: (PCTV_STD_PAL_B | PCTV_STD_NTSC_M),
        caps: bindings::V4L2_CAP_VIDEO_CAPTURE | bindings::V4L2_CAP_STREAMING
            | bindings::V4L2_CAP_READWRITE,
    }
}

fn ops_table() -> bindings::pctv_ops {
    bindings::pctv_ops {
        drvdata: core::ptr::null_mut(),
        get_fmt: Some(op_get_fmt),
        validate_fmt: Some(op_validate_fmt),
        apply_fmt: Some(op_apply_fmt),
        get_input: Some(op_get_input),
        set_input: Some(op_set_input),
        get_std: Some(op_get_std),
        set_std: Some(op_set_std),
        set_ctrl: Some(op_set_ctrl),
        get_signal: Some(op_get_signal),
        start_streaming: Some(op_start_streaming),
        stop_streaming: Some(op_stop_streaming),
    }
}

unsafe fn probe(intf: *mut bindings::usb_interface) -> Result {
    let udev = bindings::pctv_interface_to_usbdev(intf);
    if udev.is_null() {
        return Err(Error::from_errno(-ENODEV));
    }
    let ep_in = find_bulk_in_ep(intf);
    if ep_in < 0 {
        kernel::pr_warn!("no bulk-IN endpoint found\n");
        return Err(Error::from_errno(ep_in));
    }

    let mut inner = KBox::pin_init(
        pin_init!(Pctv320cxInner {
            udev,
            intf,
            glue: core::ptr::null_mut(),
            ep_in: ep_in as u8,
            urbs: [const { Urb::empty() }; NUM_URBS],
            fw_buf: core::ptr::null_mut(),
            field_buf: core::ptr::null_mut(),
            streaming: Atomic::new(false),
            dropped: Atomic::new(0),
            deframer <- new_spinlock!(Deframer::new(), "pctv320cx-deframe"),
            std_sel: STD_PAL,
            input: 0,
            fmt: bindings::pctv_fmt {
                width: 720,
                height: (PAL_LINES * 2) as u32,
                bytesperline: ACTIVE_PIXEL_BYTES as u32,
                sizeimage: (ACTIVE_PIXEL_BYTES * PAL_LINES * 2) as u32,
                field: PCTV_FIELD_INTERLACED,
                colorspace: PCTV_COLORSPACE_470BG,
            },
            clock_on: false,
            decoder_ready: false,
        }),
        kernel::alloc::flags::GFP_KERNEL,
    )?;

    // The object is pinned by pin_init; the fields touched below are only
    // written before the object is published to the C glue, and the box is
    // never moved after that (it is leaked on success, freed on the error
    // paths below).
    let d = unsafe { inner.as_mut().get_unchecked_mut() };

    d.alloc_urbs()?;

    let cookie = d as *mut Pctv320cxInner as *mut c_void;
    let mut ops = ops_table();
    ops.drvdata = cookie;

    let glue = bindings::pctv_glue_create(intf, &glue_info(), &ops);
    if glue.is_null() {
        d.free_urbs();
        return Err(Error::from_errno(-ENOMEM));
    }
    d.glue = glue;

    // Bring the hardware up.  A failure here is not fatal to the binding: the
    // device node still appears, and the error is reported, so that a missing
    // firmware file is visible instead of leaving a silent card.
    let hw = probe_hardware(d);

    if bindings::pctv_glue_register(glue) < 0 {
        d.free_urbs();
        bindings::pctv_glue_destroy(glue);
        return Err(Error::from_errno(-ENOMEM));
    }

    bindings::pctv_dev_set_drvdata(
        &mut (*intf).dev as *mut bindings::device,
        cookie,
    );
    kernel::pr_info!("Pinnacle PCTV 320cx analog capture ready\n");
    if let Err(e) = hw {
        kernel::pr_warn!("analog bring-up incomplete - capture will stay dark\n");
        let _ = e;
    }

    // The box keeps the driver object alive until disconnect() frees it.
    core::mem::forget(inner);
    Ok(())
}

unsafe fn probe_hardware(inner: &mut Pctv320cxInner) -> Result {
    // Stage by stage: a single errno at the end of probe cannot tell a dead
    // I2C tunnel apart from a missing firmware file, and both look the same
    // in the boot log.
    if let Err(e) = inner.load_bridge_firmware() {
        kernel::pr_warn!("DiB0700 firmware download failed (errno {})\n", e.to_errno());
        return Err(e);
    }
    kernel::pr_info!("DiB0700 bridge microcontroller is running\n");
    if let Err(e) = inner.board_init() {
        kernel::pr_warn!("board init failed (errno {})\n", e.to_errno());
        return Err(e);
    }
    if let Err(e) = inner.decoder_setup() {
        kernel::pr_warn!("CX25843 bring-up failed (errno {})\n", e.to_errno());
        return Err(e);
    }
    inner.demod_release_bus();
    inner.decoder_ready = true;
    Ok(())
}

unsafe fn disconnect(intf: *mut bindings::usb_interface) {
    let cookie = bindings::pctv_dev_get_drvdata(&mut (*intf).dev as *mut bindings::device);
    if cookie.is_null() {
        return;
    }
    bindings::pctv_dev_set_drvdata(&mut (*intf).dev as *mut bindings::device, core::ptr::null_mut());

    let mut inner = KBox::<Pctv320cxInner>::from_raw(cookie as *mut Pctv320cxInner);
    let glue = inner.glue;
    if !glue.is_null() {
        bindings::pctv_glue_unregister(glue);
    }
    inner.free_urbs();
    if !glue.is_null() {
        bindings::pctv_glue_destroy(glue);
    }
}

/// Entry points called by the C `struct usb_driver`.
#[no_mangle]
extern "C" fn pctv320cx_probe(
    intf: *mut bindings::usb_interface,
    _id: *const bindings::usb_device_id,
) -> c_int {
    match unsafe { probe(intf) } {
        Ok(()) => 0,
        Err(e) => e.to_errno(),
    }
}

#[no_mangle]
extern "C" fn pctv320cx_disconnect(intf: *mut bindings::usb_interface) {
    unsafe { disconnect(intf) }
}

// ---------------------------------------------------------------------------
// Module
// ---------------------------------------------------------------------------

struct Pctv320cx {}

impl kernel::Module for Pctv320cx {
    fn init(_module: &'static ThisModule) -> Result<Self> {
        let ret = unsafe { bindings::pctv_usb_register() };
        if ret < 0 {
            kernel::pr_err!("USB driver registration failed ({})\n", ret);
            return Err(Error::from_errno(ret));
        }
        Ok(Pctv320cx {})
    }
}

impl Drop for Pctv320cx {
    fn drop(&mut self) {
        unsafe { bindings::pctv_usb_unregister() }
    }
}
